source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'Coherence' do
  pod "Coherence", :path => "../"
end

target 'Tests' do
  pod "Coherence", :path => "../"
end
